### PR TITLE
Deduplicate records

### PR DESCRIPTION
**Pull request by stepps00**
Will fix a portion of https://github.com/whosonfirst-data/whosonfirst-data/issues/2181. This PR deduplicates admin records across WOF.

### CODE REVIEW

**Comment by slvlirnoff** [comment]
@stepps00 Any idea why there's some CL admin entities in this repo? Just saw this looking at a few of the file changed in this MR.

**Comment by stepps00** [comment]
@slvlirnoff Who's On First data used to be housed in a single repository, but due to size constraints, the repository was split into ~260 individual repositories. You can read more about that work [here](https://www.whosonfirst.org/blog/2019/05/09/changes/).

This "split" relied on the country codes in each Who's On First record. And because those country code values were occasionally incorrect, some records were moved to an unexpected/incorrect repository. Fast forward to March of this year, a series of PRs were merged to try to correct this issue. In general, the approach worked well to re-attribute records to the correct repository, but reviewing the diff in this PR, some follow up work may be needed.

Take this example:
- [Quemchi](https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-admin-ch/master/data/102/017/095/102017095.geojson) in the `whosonfirst-data-admin-ch` repository
- [Quemchi](https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-admin-cl/master/data/890/517/635/890517635.geojson) in the `whosonfirst-data-admin-cl` repository

The Quattroshapes source used an incorrect `ch` country code for this record, which Who's On First imported. Instead of merging these records and preferring the `cl` (Chile) repo, the `ch` repo was chosen instead (incorrectly).

The short answer is: some work is needed to migrate records to the correct Who's On First admin repository..

**Comment by slvlirnoff** [comment]
@stepps00 thanks a lot for the information!

Following these deduplicated changes, should we also update the postalcodes again after this MR? Or it has likely limited impact? I was considering updating the venues-ch too but the repository is huge 😅

**Comment by stepps00** [comment]
This issue should be limited to the admin repos, I don't think there is any work to be done in the postalcode or venue repos for Switzerland..

**Pull request merged**
